import { lazy, type ComponentType, type LazyExoticComponent } from 'react';
import type { ModuleCode } from './meta';
import type { ModuleProps } from './types';

/**
 * Lazily load a module by its named export so each panel module becomes its own
 * Vite chunk, fetched only when a panel of that type first opens. This keeps
 * heavy dependencies (e.g. lightweight-charts behind GP) out of the initial
 * bundle. Panel renders these inside a <Suspense> boundary.
 */
function mod(
  loader: () => Promise<Record<string, unknown>>,
  name: string,
): LazyExoticComponent<ComponentType<ModuleProps>> {
  return lazy(async () => ({ default: (await loader())[name] as ComponentType<ModuleProps> }));
}

/** Maps a module code to the (lazily-loaded) component that renders it. */
export const MODULE_COMPONENTS: Record<ModuleCode, LazyExoticComponent<ComponentType<ModuleProps>>> = {
  DES: mod(() => import('./DescriptionModule'), 'DescriptionModule'),
  GP: mod(() => import('./ChartModule'), 'ChartModule'),
  COMP: mod(() => import('./ComparisonModule'), 'ComparisonModule'),
  RATIO: mod(() => import('./RatioModule'), 'RatioModule'),
  PAIR: mod(() => import('./PairsModule'), 'PairsModule'),
  BOOK: mod(() => import('./OrderBookModule'), 'OrderBookModule'),
  DEPTH: mod(() => import('./OrderBookDepthHeatmapModule'), 'OrderBookDepthHeatmapModule'),
  TAS: mod(() => import('./TradesModule'), 'TradesModule'),
  CVD: mod(() => import('./OrderFlowModule'), 'OrderFlowModule'),
  IMB: mod(() => import('./ImbalanceModule'), 'ImbalanceModule'),
  LQA: mod(() => import('./LiquidityModule'), 'LiquidityModule'),
  ALLQ: mod(() => import('./MultiExchangeModule'), 'MultiExchangeModule'),
  FUND: mod(() => import('./DerivativesModule'), 'DerivativesModule'),
  FUNDR: mod(() => import('./FundingBoardModule'), 'FundingBoardModule'),
  CARRY: mod(() => import('./FundingCarryModule'), 'FundingCarryModule'),
  FPL: mod(() => import('./FundingPnlModule'), 'FundingPnlModule'),
  FRH: mod(() => import('./FundingHistoryModule'), 'FundingHistoryModule'),
  LIQS: mod(() => import('./LiquidationsModule'), 'LiquidationsModule'),
  SCR: mod(() => import('./ScreenerModule'), 'ScreenerModule'),
  HEAT: mod(() => import('./HeatmapModule'), 'HeatmapModule'),
  MOV: mod(() => import('./MarketOverviewModule'), 'MarketOverviewModule'),
  CORR: mod(() => import('./CorrelationModule'), 'CorrelationModule'),
  AVGCORR: mod(() => import('./AvgCorrModule'), 'AvgCorrModule'),
  BREADTH: mod(() => import('./BreadthModule'), 'BreadthModule'),
  BETA: mod(() => import('./BetaBoardModule'), 'BetaBoardModule'),
  CAPTURE: mod(() => import('./CaptureModule'), 'CaptureModule'),
  RBETA: mod(() => import('./RollingBetaModule'), 'RollingBetaModule'),
  SCAT: mod(() => import('./ScatterModule'), 'ScatterModule'),
  VPVR: mod(() => import('./VolumeProfileModule'), 'VolumeProfileModule'),
  SHARPE: mod(() => import('./SharpeModule'), 'SharpeModule'),
  RSHARPE: mod(() => import('./RollingSharpeModule'), 'RollingSharpeModule'),
  DD: mod(() => import('./DrawdownModule'), 'DrawdownModule'),
  CALMAR: mod(() => import('./CalmarModule'), 'CalmarModule'),
  CAL: mod(() => import('./CalendarModule'), 'CalendarModule'),
  VOL: mod(() => import('./VolatilityModule'), 'VolatilityModule'),
  VAR: mod(() => import('./DistributionModule'), 'DistributionModule'),
  SKEW: mod(() => import('./ShapeModule'), 'ShapeModule'),
  VTS: mod(() => import('./VolTermModule'), 'VolTermModule'),
  VCONE: mod(() => import('./VolConesModule'), 'VolConesModule'),
  MC: mod(() => import('./MonteCarloModule'), 'MonteCarloModule'),
  BACKTEST: mod(() => import('./BacktestModule'), 'BacktestModule'),
  MOM: mod(() => import('./MomentumModule'), 'MomentumModule'),
  STRETCH: mod(() => import('./StretchModule'), 'StretchModule'),
  HURST: mod(() => import('./HurstModule'), 'HurstModule'),
  EFFICIENCY: mod(() => import('./EfficiencyModule'), 'EfficiencyModule'),
  SCAN: mod(() => import('./ScanModule'), 'ScanModule'),
  MTF: mod(() => import('./MtfModule'), 'MtfModule'),
  RRG: mod(() => import('./RotationModule'), 'RotationModule'),
  SEAS: mod(() => import('./SeasonalityModule'), 'SeasonalityModule'),
  MRET: mod(() => import('./MonthlyReturnsModule'), 'MonthlyReturnsModule'),
  RCAL: mod(() => import('./ReturnsCalendarModule'), 'ReturnsCalendarModule'),
  PREM: mod(() => import('./BasisModule'), 'BasisModule'),
  ARB: mod(() => import('./ArbModule'), 'ArbModule'),
  SLIP: mod(() => import('./SlippageModule'), 'SlippageModule'),
  TWAP: mod(() => import('./TwapModule'), 'TwapModule'),
  AI: mod(() => import('./AiCopilotModule'), 'AiCopilotModule'),
  W: mod(() => import('./WatchlistModule'), 'WatchlistModule'),
  Q: mod(() => import('./QuoteMonitorModule'), 'QuoteMonitorModule'),
  PORT: mod(() => import('./PortfolioModule'), 'PortfolioModule'),
  RHEAT: mod(() => import('./PortfolioRiskModule'), 'PortfolioRiskModule'),
  EXP: mod(() => import('./ExposureModule'), 'ExposureModule'),
  PBETA: mod(() => import('./PortfolioBetaModule'), 'PortfolioBetaModule'),
  REBAL: mod(() => import('./RebalanceModule'), 'RebalanceModule'),
  ALERT: mod(() => import('./AlertsModule'), 'AlertsModule'),
  NOTE: mod(() => import('./NotesModule'), 'NotesModule'),
  RISK: mod(() => import('./RiskModule'), 'RiskModule'),
  CONV: mod(() => import('./SizeConverterModule'), 'SizeConverterModule'),
  KELLY: mod(() => import('./KellyModule'), 'KellyModule'),
  ROR: mod(() => import('./RorModule'), 'RorModule'),
  LADDER: mod(() => import('./LadderModule'), 'LadderModule'),
  DCA: mod(() => import('./DcaModule'), 'DcaModule'),
  LOG: mod(() => import('./JournalModule'), 'JournalModule'),
  EQ: mod(() => import('./EquityModule'), 'EquityModule'),
  PNL: mod(() => import('./PnlModule'), 'PnlModule'),
  ACCT: mod(() => import('./AccountModule'), 'AccountModule'),
  PREF: mod(() => import('./SettingsModule'), 'SettingsModule'),
  REPORT: mod(() => import('./ReportModule'), 'ReportModule'),
  N: mod(() => import('./NewsModule'), 'NewsModule'),
  HELP: mod(() => import('./HelpModule'), 'HelpModule'),
  SECF: mod(() => import('./SecurityFinderModule'), 'SecurityFinderModule'),
};
