import type { ModuleCode } from '@/modules/meta';
import type { PanelParams } from '@/store/usePanels';

/** A terminal command (Bloomberg-style mnemonic) the user can type. */
export interface CommandDef {
  code: string;
  aliases: string[];
  title: string;
  /** Which module/panel this command opens. */
  module: ModuleCode;
  /** If true, the command operates on a security and needs a symbol. */
  requiresSymbol: boolean;
  description: string;
  /** Default params handed to the module (e.g. chart interval/range). */
  params?: PanelParams;
}

export const COMMANDS: CommandDef[] = [
  {
    code: 'DES',
    aliases: ['DESC', 'DS'],
    title: 'Security Description',
    module: 'DES',
    requiresSymbol: true,
    description: 'Snapshot quote, key stats and session detail for a security.',
  },
  {
    code: 'GP',
    aliases: ['CHART', 'G', 'GRAPH'],
    title: 'Price Graph',
    module: 'GP',
    requiresSymbol: true,
    description: 'Historical price chart (daily candles).',
    params: { interval: '1d', range: '6mo' },
  },
  {
    code: 'GIP',
    aliases: ['INTRADAY'],
    title: 'Intraday Graph',
    module: 'GP',
    requiresSymbol: true,
    description: 'Intraday price chart (5-minute candles).',
    params: { interval: '5m', range: '1d' },
  },
  {
    code: 'HP',
    aliases: ['HISTORY', 'HISTPX', 'OHLC'],
    title: 'Historical Prices',
    module: 'HP',
    requiresSymbol: true,
    description:
      'Historical prices — a tabular OHLCV history per bar (open/high/low/close, change% vs the prior close, volume) with 5D / 1M / 3M / 1Y / 5Y lookbacks, a period summary (high/low, total change, avg volume, up/down days) and sortable date / change% / volume columns. The data-table complement to the chart (G / GIP).',
  },
  {
    code: 'COMP',
    aliases: ['COMPARE', 'CMP', 'REL'],
    title: 'Compare',
    module: 'COMP',
    requiresSymbol: false,
    description: 'Overlay several symbols rebased to % change to compare performance.',
    params: { interval: '1d', range: '6mo' },
  },
  {
    code: 'RATIO',
    aliases: ['SPREAD'],
    title: 'Ratio / Spread',
    module: 'RATIO',
    requiresSymbol: false,
    description: 'Chart the ratio (A/B) or spread (A−B) between two symbols over time.',
    params: { interval: '1d', range: '6mo' },
  },
  {
    code: 'PAIR',
    aliases: ['PAIRS', 'ZSCORE', 'STATARB'],
    title: 'Pairs Z-Score',
    module: 'PAIR',
    requiresSymbol: false,
    description: 'Pairs / stat-arb monitor — ratio of two symbols with rolling mean ±σ bands, a z-score oscillator and mean-reversion half-life.',
  },
  {
    code: 'BOOK',
    aliases: ['DOM', 'OB'],
    title: 'Order Book',
    module: 'BOOK',
    requiresSymbol: true,
    description: 'Live Level-2 order book / depth of market (best on crypto).',
  },
  {
    code: 'DEPTH',
    aliases: ['DHEAT', 'OBHEAT', 'DOMHEAT'],
    title: 'Depth Heatmap',
    module: 'DEPTH',
    requiresSymbol: true,
    description: 'Order-book depth heatmap — resting liquidity over time as a price × time grid, with the mid track.',
  },
  {
    code: 'TAS',
    aliases: ['PRINTS', 'TS', 'TRADES'],
    title: 'Time & Sales',
    module: 'TAS',
    requiresSymbol: true,
    description: 'Live streaming trade prints (time & sales).',
  },
  {
    code: 'CVD',
    aliases: ['FLOW', 'OFD', 'DELTA'],
    title: 'Order Flow',
    module: 'CVD',
    requiresSymbol: true,
    description: 'Order-flow / cumulative volume delta — buy vs sell pressure over time with a per-window delta histogram.',
  },
  {
    code: 'IMB',
    aliases: ['IMBALANCE', 'OBI', 'PRESSURE'],
    title: 'Book Imbalance',
    module: 'IMB',
    requiresSymbol: true,
    description: 'Order-book imbalance — top-N bid vs ask depth pressure over time with a live gauge.',
  },
  {
    code: 'LQA',
    aliases: ['LIQUIDITY', 'SPREADS', 'MKTQUAL'],
    title: 'Liquidity',
    module: 'LQA',
    requiresSymbol: false,
    description: 'Liquidity board — watchlist ranked by bid/ask spread (bps) and top-of-book depth.',
  },
  {
    code: 'ALLQ',
    aliases: ['XQ', 'VENUES'],
    title: 'Multi-Exchange Quotes',
    module: 'ALLQ',
    requiresSymbol: true,
    description: 'Compare a pair across exchanges — best bid/ask and cross-exchange spread.',
  },
  {
    code: 'FUND',
    aliases: ['OI', 'LIQ', 'PERP'],
    title: 'Derivatives',
    module: 'FUND',
    requiresSymbol: true,
    description: 'Perp funding rate, open interest and recent liquidations.',
  },
  {
    code: 'FUNDR',
    aliases: ['RATES', 'CARRY'],
    title: 'Funding Rates',
    module: 'FUNDR',
    requiresSymbol: false,
    description: 'Funding rates & open interest across the top perps — sortable board.',
  },
  {
    code: 'LIQS',
    aliases: ['LIQUIDATIONS', 'REKT'],
    title: 'Liquidations',
    module: 'LIQS',
    requiresSymbol: false,
    description: 'Market-wide liquidations feed across the top perps.',
  },
  {
    code: 'SCR',
    aliases: ['EQS', 'SCREEN', 'MOVERS'],
    title: 'Screener',
    module: 'SCR',
    requiresSymbol: false,
    description: 'Screen crypto markets by volume, 24h change or price.',
  },
  {
    code: 'HEAT',
    aliases: ['MAP', 'HM'],
    title: 'Market Heatmap',
    module: 'HEAT',
    requiresSymbol: false,
    description: 'Treemap of the market — tiles sized by volume, colored by 24h change.',
  },
  {
    code: 'MOV',
    aliases: ['OVERVIEW'],
    title: 'Market Overview',
    module: 'MOV',
    requiresSymbol: false,
    description: 'Market dashboard — top gainers, losers, most active and breadth.',
  },
  {
    code: 'CORR',
    aliases: ['COR', 'CORREL'],
    title: 'Correlation Matrix',
    module: 'CORR',
    requiresSymbol: false,
    description: 'Return-correlation grid across your watchlist symbols.',
  },
  {
    code: 'AVGCORR',
    aliases: ['AVGCOR', 'CORRREGIME', 'MEANCORR'],
    title: 'Correlation Regime',
    module: 'AVGCORR',
    requiresSymbol: false,
    description: 'Average-correlation regime — mean pairwise correlation across your watchlist over time; high = risk-off, low = dispersion.',
  },
  {
    code: 'BREADTH',
    aliases: ['ADLINE', 'PARTICIPATION', 'ABOVEMA'],
    title: 'Breadth Oscillator',
    module: 'BREADTH',
    requiresSymbol: false,
    description: 'Market-breadth oscillator — the % of your watchlist above its N-day moving average over time; high = broad strength, low = weakness.',
  },
  {
    code: 'BETA',
    aliases: ['BTCBETA', 'BETAS'],
    title: 'Beta vs BTC',
    module: 'BETA',
    requiresSymbol: false,
    description: 'Beta board — each watchlist symbol’s beta, correlation and R² vs BTC from daily returns.',
  },
  {
    code: 'CAPTURE',
    aliases: ['UPDOWN', 'CAPRATIO', 'UPCAPTURE'],
    title: 'Up/Down Capture',
    module: 'CAPTURE',
    requiresSymbol: false,
    description: 'Up/down capture vs BTC — how much of BTC’s up vs down moves each watchlist symbol catches, with the capture ratio.',
  },
  {
    code: 'RBETA',
    aliases: ['ROLLBETA', 'RCORR', 'BETAHIST'],
    title: 'Rolling Beta',
    module: 'RBETA',
    requiresSymbol: true,
    description: 'Rolling beta & correlation vs BTC — how a symbol’s sensitivity to Bitcoin drifts over a trailing window.',
  },
  {
    code: 'SCAT',
    aliases: ['SCATTER', 'REGRESS', 'BETAPLOT'],
    title: 'Returns Scatter',
    module: 'SCAT',
    requiresSymbol: true,
    description: 'Returns scatter vs BTC — daily returns with the fitted regression line (beta, alpha, R²).',
  },
  {
    code: 'VPVR',
    aliases: ['VP', 'VOLPROFILE', 'VBP'],
    title: 'Volume Profile',
    module: 'VPVR',
    requiresSymbol: true,
    description: 'Volume profile (VPVR) — traded volume binned by price with the Point of Control and 70% value area (VAH/VAL).',
  },
  {
    code: 'SHARPE',
    aliases: ['SORTINO', 'RISKADJ', 'RAR'],
    title: 'Risk-Adjusted',
    module: 'SHARPE',
    requiresSymbol: false,
    description: 'Risk-adjusted return board — Sharpe & Sortino (annualized) with annualized return and vol across your watchlist.',
  },
  {
    code: 'RSHARPE',
    aliases: ['ROLLSHARPE', 'RSHARP', 'SHARPEHIST'],
    title: 'Rolling Sharpe',
    module: 'RSHARPE',
    requiresSymbol: true,
    description: 'Rolling Sharpe — the trailing annualized risk-adjusted return over a moving window, showing when an edge strengthened or decayed.',
  },
  {
    code: 'DD',
    aliases: ['DRAWDOWN', 'UNDERWATER', 'MDD'],
    title: 'Drawdown',
    module: 'DD',
    requiresSymbol: false,
    description: 'Drawdown monitor — max & current drawdown, time underwater and an underwater curve across your watchlist.',
  },
  {
    code: 'CALMAR',
    aliases: ['MARRATIO', 'RETDD', 'CALMARRATIO'],
    title: 'Calmar Ratio',
    module: 'CALMAR',
    requiresSymbol: false,
    description: 'Calmar-ratio board — annualized return ÷ max drawdown across your watchlist, ranking return per unit of worst drawdown.',
  },
  {
    code: 'CAL',
    aliases: ['CALENDAR', 'EVENTS', 'ECON'],
    title: 'Market Calendar',
    module: 'CAL',
    requiresSymbol: false,
    description: 'Upcoming market timing — funding settlements, options/futures expiries and candle closes.',
  },
  {
    code: 'VOL',
    aliases: ['VOLATILITY', 'ATR', 'RV'],
    title: 'Volatility',
    module: 'VOL',
    requiresSymbol: false,
    description: 'Volatility dashboard — realized vol, ATR and high-low range ranked across your watchlist.',
  },
  {
    code: 'VAR',
    aliases: ['DIST', 'HIST', 'CVAR'],
    title: 'Returns / VaR',
    module: 'VAR',
    requiresSymbol: true,
    description: 'Return distribution & risk — histogram with vol, skew, kurtosis and historical VaR / expected shortfall.',
  },
  {
    code: 'SKEW',
    aliases: ['SHAPE', 'KURTOSIS', 'TAILS'],
    title: 'Return Shape',
    module: 'SKEW',
    requiresSymbol: false,
    description: 'Return-shape board — skewness & excess kurtosis of each watchlist symbol’s daily returns, flagging fat-tailed & asymmetric names.',
  },
  {
    code: 'VTS',
    aliases: ['VOLTERM', 'TERM', 'VTERM'],
    title: 'Vol Term Structure',
    module: 'VTS',
    requiresSymbol: true,
    description: 'Volatility term structure — realized vol across 7d…180d lookbacks, flagging rich/cheap near-term vol.',
  },
  {
    code: 'VCONE',
    aliases: ['VOLCONE', 'VCONES', 'RVCONE'],
    title: 'Vol Cones',
    module: 'VCONE',
    requiresSymbol: true,
    description: 'Volatility cones — realized-vol percentiles across 10…120d horizons with the current vol overlaid, flagging rich/cheap.',
  },
  {
    code: 'MC',
    aliases: ['MONTECARLO', 'PROJECT', 'CONE'],
    title: 'Monte Carlo',
    module: 'MC',
    requiresSymbol: true,
    description: 'Monte Carlo projection cone — GBM price forecast fan (5–95 percentiles) from historical drift & vol.',
  },
  {
    code: 'BACKTEST',
    aliases: ['BT', 'STRATEGY', 'SMACROSS', 'RSIBT', 'BOLLBT', 'MACDBT'],
    title: 'Backtest',
    module: 'BACKTEST',
    requiresSymbol: true,
    description: 'Strategy backtest — SMA-crossover, RSI mean-reversion, Bollinger-band reversion or MACD crossover: strategy equity vs buy & hold with total return, max drawdown, win rate & trade count.',
  },
  {
    code: 'MOM',
    aliases: ['MOMENTUM', 'RS', 'STRENGTH'],
    title: 'Momentum',
    module: 'MOM',
    requiresSymbol: false,
    description: 'Momentum / relative-strength board — 24h/7d/30d returns ranked across your watchlist.',
  },
  {
    code: 'STRETCH',
    aliases: ['OVERSOLD', 'BBANDS', 'MEANREV'],
    title: 'Stretch Screener',
    module: 'STRETCH',
    requiresSymbol: false,
    description: 'Mean-reversion screener — watchlist ranked by z-score & Bollinger %B vs its moving average, flagging overbought/oversold.',
  },
  {
    code: 'HURST',
    aliases: ['REGIME', 'TRENDREV', 'FRACTAL'],
    title: 'Trend / Revert',
    module: 'HURST',
    requiresSymbol: false,
    description: 'Trend vs mean-reversion board — each watchlist symbol’s Hurst exponent (R/S) classifying trending, mean-reverting or random-walk.',
  },
  {
    code: 'EFFICIENCY',
    aliases: ['EFFRATIO', 'KER'],
    title: 'Trend Efficiency',
    module: 'EFFICIENCY',
    requiresSymbol: false,
    description: 'Trend-efficiency board — Kaufman’s Efficiency Ratio (net move ÷ path) ranks how clean vs choppy each watchlist symbol’s trend is.',
  },
  {
    code: 'SCAN',
    aliases: ['SCANNER', 'SIGNALS', 'SETUP'],
    title: 'Signal Scan',
    module: 'SCAN',
    requiresSymbol: false,
    description: 'Signal scanner — watchlist SMA20/50 trend, RSI(14) overbought/oversold and 52-week range position, ranked by a bull/bear score.',
  },
  {
    code: 'MTF',
    aliases: ['MULTITF', 'TIMEFRAMES', 'MTREND'],
    title: 'Multi-Timeframe',
    module: 'MTF',
    requiresSymbol: true,
    description: 'Multi-timeframe trend — SMA trend & RSI across 1H/1D/1W/1M with a consensus read of whether the frames are in gear.',
  },
  {
    code: 'RRG',
    aliases: ['ROTATION', 'ROT'],
    title: 'Rotation (RRG)',
    module: 'RRG',
    requiresSymbol: false,
    description: 'Relative rotation graph — watchlist symbols by RS-Ratio × RS-Momentum vs BTC, with rotation tails.',
  },
  {
    code: 'SEAS',
    aliases: ['SEASON', 'SEASONALITY', 'TOD'],
    title: 'Seasonality',
    module: 'SEAS',
    requiresSymbol: true,
    description: 'Returns seasonality — average return by UTC hour-of-day and day-of-week as a heat grid.',
  },
  {
    code: 'MRET',
    aliases: ['MONTHLY', 'MRETURNS', 'CALRET'],
    title: 'Monthly Returns',
    module: 'MRET',
    requiresSymbol: true,
    description: 'Monthly returns heatmap — month-over-month % as a year × month grid with compounded year totals.',
  },
  {
    code: 'RCAL',
    aliases: ['RETCAL', 'DRET', 'DAILYRET'],
    title: 'Returns Calendar',
    module: 'RCAL',
    requiresSymbol: true,
    description: 'Daily returns calendar — a contribution-style heatmap of daily % returns with best/worst day, positive-day rate and current streak.',
  },
  {
    code: 'CARRY',
    aliases: ['CASHCARRY', 'CARRYTRADE'],
    title: 'Funding Carry',
    module: 'CARRY',
    requiresSymbol: false,
    description: 'Funding-carry board — perps ranked by funding APR with spot-vs-perp basis and the carry leg.',
  },
  {
    code: 'FPL',
    aliases: ['FUNDPNL', 'CARRYPNL', 'FPNL'],
    title: 'Funding P&L',
    module: 'FPL',
    requiresSymbol: true,
    description: 'Funding P&L forecaster — project a perp position’s carry over a horizon at the current funding rate.',
  },
  {
    code: 'FRH',
    aliases: ['FUNDHIST', 'FRATE', 'FUNDINGHIST'],
    title: 'Funding History',
    module: 'FRH',
    requiresSymbol: true,
    description: 'Funding-rate history — a perp’s funding settlements over time with the average and current APR.',
  },
  {
    code: 'PREM',
    aliases: ['PREMIUM', 'SPREAD'],
    title: 'Basis Monitor',
    module: 'PREM',
    requiresSymbol: true,
    description: 'Perp basis monitor — premium vs spot, funding rate & APR, with a live premium history.',
  },
  {
    code: 'ARB',
    aliases: ['ARBITRAGE', 'XSPREAD'],
    title: 'Arb Scanner',
    module: 'ARB',
    requiresSymbol: true,
    description: 'Cross-exchange arb scanner — best bid/ask across venues, spread % and crossed-book flag.',
  },
  {
    code: 'SLIP',
    aliases: ['SLIPPAGE', 'IMPACT'],
    title: 'Slippage',
    module: 'SLIP',
    requiresSymbol: true,
    description: 'Slippage estimator — average fill & market impact for an order size, walking the live book.',
  },
  {
    code: 'TWAP',
    aliases: ['EXEC', 'ALGO', 'SLICE'],
    title: 'Execution (TWAP)',
    module: 'TWAP',
    requiresSymbol: true,
    description: 'TWAP execution planner — slice a large order over time and compare impact vs an aggressive block.',
  },
  {
    code: 'AI',
    aliases: ['ASK', 'COPILOT'],
    title: 'AI Copilot',
    module: 'AI',
    requiresSymbol: false,
    description: 'Ask Claude about the market — grounded in your terminal’s live data.',
  },
  {
    code: 'W',
    aliases: ['WATCH', 'WL'],
    title: 'Watchlist',
    module: 'W',
    requiresSymbol: false,
    description: 'Your personal watchlist of securities.',
  },
  {
    code: 'Q',
    aliases: ['QM', 'QUOTE'],
    title: 'Quote Monitor',
    module: 'Q',
    requiresSymbol: false,
    description: 'Live quote grid for your watchlist symbols.',
  },
  {
    code: 'PORT',
    aliases: ['POS', 'PORTFOLIO'],
    title: 'Portfolio',
    module: 'PORT',
    requiresSymbol: false,
    description: 'Paper portfolio — track positions and live unrealized P&L.',
  },
  {
    code: 'RHEAT',
    aliases: ['EXPOSURE', 'PRISK'],
    title: 'Position Risk',
    module: 'RHEAT',
    requiresSymbol: false,
    description: 'Portfolio risk heat — per-position P&L, exposure and liquidation distance across your book.',
  },
  {
    code: 'EXP',
    aliases: ['EXPO', 'WEIGHTS', 'GROSS'],
    title: 'Exposure',
    module: 'EXP',
    requiresSymbol: false,
    description: 'Portfolio exposure breakdown — net/gross, long vs short, per-asset weights, leverage and concentration.',
  },
  {
    code: 'PBETA',
    aliases: ['PORTBETA', 'BWEIGHT', 'NETBETA'],
    title: 'Portfolio Beta',
    module: 'PBETA',
    requiresSymbol: false,
    description: 'Beta-weighted portfolio exposure to BTC — collapse the book into one BTC-equivalent delta with per-position contributions.',
  },
  {
    code: 'REBAL',
    aliases: ['REBALANCE', 'RETARGET', 'ALLOCATE'],
    title: 'Rebalance',
    module: 'REBAL',
    requiresSymbol: false,
    description: 'Rebalance calculator — set target weights for your holdings and get the buy/sell trades, per-position drift and turnover.',
  },
  {
    code: 'RPARITY',
    aliases: ['RISKPARITY', 'PARITY', 'INVVOL'],
    title: 'Risk Parity',
    module: 'RPARITY',
    requiresSymbol: false,
    description: 'Risk-parity weights — inverse-volatility target weights for your watchlist so every name contributes equal risk.',
  },
  {
    code: 'OPT',
    aliases: ['MINVAR', 'GMV', 'OPTIMIZE'],
    title: 'Min Variance',
    module: 'OPT',
    requiresSymbol: false,
    description: 'Minimum-variance optimizer — covariance-aware target weights (w = Σ⁻¹·1 / 1ᵀΣ⁻¹·1) for the lowest-variance fully-invested watchlist book.',
  },
  {
    code: 'MSR',
    aliases: ['TANGENCY', 'MAXSHARPE', 'SHARPEOPT'],
    title: 'Max Sharpe',
    module: 'MSR',
    requiresSymbol: false,
    description: 'Max-Sharpe (tangency) optimizer — covariance-aware target weights (w ∝ Σ⁻¹·(μ−rf)) for the highest risk-adjusted-return fully-invested watchlist book.',
  },
  {
    code: 'FRONTIER',
    aliases: ['EF', 'EFFRONTIER', 'CML'],
    title: 'Efficient Frontier',
    module: 'FRONTIER',
    requiresSymbol: false,
    description: 'Markowitz efficient frontier — plots the risk/return frontier for your watchlist with the GMV (min-variance) and tangency (max-Sharpe) portfolios, the equal-weight book and each asset.',
  },
  {
    code: 'RISKB',
    aliases: ['RISKBUDGET', 'MCTR', 'RBUDGET'],
    title: 'Risk Budget',
    module: 'RISKB',
    requiresSymbol: false,
    description: 'Risk-budget board — decomposes your portfolio variance into each holding’s marginal and percent contribution to risk (MCTR), so you see which names drive the swings vs their weight.',
  },
  {
    code: 'ULCER',
    aliases: ['UI', 'ULCERINDEX'],
    title: 'Ulcer Index',
    module: 'ULCER',
    requiresSymbol: false,
    description: 'Ulcer Index board — ranks watchlist drawdown pain (depth × duration, RMS of drawdowns) with the Martin ratio (annualized return ÷ Ulcer).',
  },
  {
    code: 'GPR',
    aliases: ['GAINPAIN', 'GAINTOPAIN', 'G2P'],
    title: 'Gain to Pain',
    module: 'GPR',
    requiresSymbol: false,
    description: 'Gain-to-Pain board — ranks watchlist return quality by Σ returns ÷ Σ losses (Schwager GPR): how much net return per unit of downside endured.',
  },
  {
    code: 'OMEGA',
    aliases: ['OMG', 'OMEGARATIO'],
    title: 'Omega Ratio',
    module: 'OMEGA',
    requiresSymbol: false,
    description: 'Omega ratio board — ranks watchlist names by Σ gains above a threshold ÷ Σ shortfalls below it; a full-distribution alternative to Sharpe with an adjustable τ.',
  },
  {
    code: 'DIVR',
    aliases: ['DIVERSIFICATION', 'DIVRATIO'],
    title: 'Diversification',
    module: 'DIVR',
    requiresSymbol: false,
    description: 'Diversification ratio — weighted-avg asset vol ÷ portfolio vol for the equal-weight watchlist book, with the effective number of independent bets (DR²).',
  },
  {
    code: 'TAIL',
    aliases: ['TAILRATIO', 'TAILS'],
    title: 'Tail Ratio',
    module: 'TAIL',
    requiresSymbol: false,
    description: 'Tail-ratio board — |95th pct| ÷ |5th pct| of returns per watchlist name: whether the extreme moves favor the upside (>1) or the downside (<1).',
  },
  {
    code: 'PAIN',
    aliases: ['PAININDEX', 'PAINRATIO'],
    title: 'Pain Index',
    module: 'PAIN',
    requiresSymbol: false,
    description: 'Pain Index board — ranks watchlist average drawdown depth (mean underwater) with the Pain ratio (annualized return ÷ Pain Index).',
  },
  {
    code: 'KRATIO',
    aliases: ['KRAT', 'KESTNER'],
    title: 'K-Ratio',
    module: 'KRATIO',
    requiresSymbol: false,
    description: 'K-ratio board — Kestner trend-consistency: the log-price trend slope ÷ its standard error (a t-stat), ranking watchlist names by how steady their climb is.',
  },
  {
    code: 'VREG',
    aliases: ['VOLREGIME', 'VOLREG'],
    title: 'Vol Regime',
    module: 'VREG',
    requiresSymbol: false,
    description: 'Vol-regime board — short-window ÷ long-window realized volatility per watchlist name (expanding >1 / contracting <1), with the percentile of today’s vol in its own history.',
  },
  {
    code: 'ACF',
    aliases: ['AUTOCORR', 'AUTOCORRELATION'],
    title: 'Autocorrelation',
    module: 'ACF',
    requiresSymbol: false,
    description: 'Autocorrelation board — lag-1/2/3 return autocorrelation per watchlist name: positive = momentum (returns persist), negative = mean-reverting (returns reverse).',
  },
  {
    code: 'STERLING',
    aliases: ['STERLINGRATIO', 'STERL'],
    title: 'Sterling Ratio',
    module: 'STERLING',
    requiresSymbol: false,
    description: 'Sterling ratio board — annualized return ÷ (average drawdown + 10%): a drawdown risk-adjusted return that averages drawdown episodes (vs Calmar’s single worst).',
  },
  {
    code: 'INFO',
    aliases: ['INFORATIO', 'IR'],
    title: 'Information Ratio',
    module: 'INFO',
    requiresSymbol: false,
    description: 'Information-ratio board — each watchlist name’s active return over BTC ÷ its tracking error: how much excess return per unit of benchmark-relative risk.',
  },
  {
    code: 'BURKE',
    aliases: ['BURKERATIO'],
    title: 'Burke Ratio',
    module: 'BURKE',
    requiresSymbol: false,
    description: 'Burke ratio board — annualized return ÷ √(Σ drawdown²): the root-sum-square of drawdown-episode depths penalizes deep and frequent drawdowns more than Sterling’s average or Calmar’s single worst.',
  },
  {
    code: 'TREYNOR',
    aliases: ['TREYNORRATIO'],
    title: 'Treynor Ratio',
    module: 'TREYNOR',
    requiresSymbol: false,
    description: 'Treynor ratio board — annualized return ÷ beta-to-BTC: return per unit of systematic (market) risk. Completes the Sharpe (total risk) / Information (active risk) / Treynor (beta) trio.',
  },
  {
    code: 'ALPHA',
    aliases: ['JENSEN', 'JALPHA'],
    title: "Jensen's Alpha",
    module: 'ALPHA',
    requiresSymbol: false,
    description: "Jensen's alpha board — annualized return minus the CAPM-predicted return (beta·BTC-return): the excess a name delivers beyond what its BTC exposure alone explains. Positive = genuine outperformance.",
  },
  {
    code: 'APPRAISAL',
    aliases: ['APPR', 'APRATIO'],
    title: 'Appraisal Ratio',
    module: 'APPRAISAL',
    requiresSymbol: false,
    description: "Appraisal ratio board — Jensen's alpha ÷ idiosyncratic (residual) volatility: stock-specific outperformance per unit of the diversifiable risk taken to get it (Treynor–Black).",
  },
  {
    code: 'M2',
    aliases: ['MODIGLIANI', 'MSQUARED'],
    title: 'M² (Modigliani)',
    module: 'M2',
    requiresSymbol: false,
    description: "M² (Modigliani) board — each name's return rescaled to BTC's volatility (Sharpe × σ_BTC): what it would have returned at the market's risk level, in directly comparable return units.",
  },
  {
    code: 'CSR',
    aliases: ['COMMONSENSE', 'CSRATIO'],
    title: 'Common-Sense Ratio',
    module: 'CSR',
    requiresSymbol: false,
    description: 'Common-sense ratio board — tail ratio × gain-to-pain: rewards a name only when it has both a fat right tail and an efficient win/loss balance. ≥1 is the green light.',
  },
  {
    code: 'RSTAB',
    aliases: ['SHARPESTAB', 'STAB'],
    title: 'Rolling-Sharpe Stability',
    module: 'RSTAB',
    requiresSymbol: false,
    description: 'Rolling-Sharpe stability board — mean ÷ stdev of each name’s rolling-Sharpe series: ranks who delivers a consistent risk-adjusted edge vs whose edge flickers. High and steady beats high and erratic.',
  },
  {
    code: 'ASR',
    aliases: ['ADJSHARPE', 'ADJUSTEDSHARPE'],
    title: 'Adjusted Sharpe',
    module: 'ASR',
    requiresSymbol: false,
    description: 'Adjusted Sharpe ratio board (Pezier-White) — the Sharpe penalized for negative skew and excess kurtosis: docks names whose smooth Sharpe hides a fat left tail, rewards genuinely well-shaped returns.',
  },
  {
    code: 'BETAETH',
    aliases: ['EBETA', 'BETAVS'],
    title: 'Beta vs ETH / BTC',
    module: 'BETAETH',
    requiresSymbol: false,
    description: 'Dual-beta board — each name’s beta to ETH and to BTC over the same window, plus their divergence (βETH − βBTC): surfaces ETH-leaning vs BTC-leaning names across the watchlist.',
  },
  {
    code: 'MARTIN',
    aliases: ['UPI', 'MARTINRATIO'],
    title: 'Martin Ratio (UPI)',
    module: 'MARTIN',
    requiresSymbol: false,
    description: 'Martin ratio (Ulcer Performance Index) term structure — annualized return ÷ Ulcer Index across 1M/3M/6M/1Y trailing windows: return per unit of drawdown pain, read as a curve over horizon.',
  },
  {
    code: 'LEADLAG',
    aliases: ['LEAD', 'XCORR'],
    title: 'Lead-Lag vs BTC',
    module: 'LEADLAG',
    requiresSymbol: false,
    description: 'Lead-lag board — the lag of peak cross-correlation between each name and BTC: negative = the name leads BTC (moves first), positive = it lags. Finds early-warning tells and followers.',
  },
  {
    code: 'DDREC',
    aliases: ['RECOVERY', 'TTR'],
    title: 'Drawdown Recovery',
    module: 'DDREC',
    requiresSymbol: false,
    description: 'Drawdown recovery board — days underwater per name: current unresolved drawdown, longest underwater stretch, and average time to recover past drawdowns. Ranks how long pain lasts, not just how deep.',
  },
  {
    code: 'VOV',
    aliases: ['VOLOFVOL', 'VOVOL'],
    title: 'Vol of Vol',
    module: 'VOV',
    requiresSymbol: false,
    description: 'Vol-of-vol board — the coefficient of variation of each name’s rolling volatility (stdev ÷ mean of the rolling vol): ranks whose risk level itself is stable vs whose whipsaws between calm and chaos.',
  },
  {
    code: 'STREAK',
    aliases: ['STREAKS', 'RUNS'],
    title: 'Up/Down Streaks',
    module: 'STREAK',
    requiresSymbol: false,
    description: 'Up/down streak board — current signed run (+up / −down days), longest up and down runs, and the share of up days per name: momentum-persistence and capitulation tells from the raw return signs.',
  },
  {
    code: 'RANGE',
    aliases: ['NR7', 'EXPANSION', 'RNG'],
    title: 'Range Expansion',
    module: 'RANGE',
    requiresSymbol: false,
    description: 'Range-expansion / NR7 board — each name’s latest true range vs its trailing average: EXP ratio (>1 expanding, <1 coiling), today’s range as a % of price, and its rank among the last 7 days (NR7 = narrowest, a coiled-spring breakout setup).',
  },
  {
    code: 'UVOL',
    aliases: ['RVOL', 'SURGE', 'VOLSURGE'],
    title: 'Unusual Volume',
    module: 'UVOL',
    requiresSymbol: false,
    description: 'Unusual-volume board — each name’s latest volume vs its trailing average: RVOL (relative volume, today ÷ avg), a z-score vs that window, and the day’s direction so a spike reads as accumulation (▲ up-day) or distribution (▼ down-day).',
  },
  {
    code: 'GAP',
    aliases: ['GAPS', 'GAPFILL'],
    title: 'Gap Board',
    module: 'GAP',
    requiresSymbol: false,
    description: 'Gap board — each name’s open-vs-prior-close jump at the daily roll: today’s signed gap, the typical (average absolute) gap size, the same-day fill rate (how often price retraces to the prior close), and the net up − down gap bias.',
  },
  {
    code: 'HILO',
    aliases: ['PROXIMITY', 'NEARHIGH'],
    title: 'High/Low Proximity',
    module: 'HILO',
    requiresSymbol: false,
    description: 'High/low proximity board — where each name’s close sits in its N-day range (POS 0 = low → 100 = high), how far it is below the period high and above the period low, and a new-high / new-low flag. Spot names pressing a breakout vs basing near support.',
  },
  {
    code: 'OBV',
    aliases: ['ACCUM', 'ACCUMULATION'],
    title: 'OBV / Accumulation',
    module: 'OBV',
    requiresSymbol: false,
    description: 'On-balance-volume board — cumulative signed volume per name with its net up − down volume flow and the OBV trend (regression slope ÷ avg volume): ranks who is being accumulated (volume confirming up moves) vs distributed.',
  },
  {
    code: 'CHOP',
    aliases: ['CHOPPINESS', 'CHOPPY'],
    title: 'Choppiness Index',
    module: 'CHOP',
    requiresSymbol: false,
    description: 'Choppiness Index board — Dreiss’ 0–100 gauge of trending vs ranging per name (Σ true range ÷ net span, log-normalized): below ~38 is a clean trend, above ~62 is sideways chop. A regime filter that pairs with RANGE / NR7.',
  },
  {
    code: 'BB',
    aliases: ['BOLL', 'PCTB', 'SQUEEZE'],
    title: 'Bollinger %B',
    module: 'BB',
    requiresSymbol: false,
    description: 'Bollinger %B board — each name’s position within its Bollinger bands (%B: 0 = lower, 0.5 = middle, 1 = upper), the band width relative to price, and a squeeze flag when bandwidth sits in the bottom quintile of its recent range (compression before expansion).',
  },
  {
    code: 'RSI',
    aliases: ['RSI14', 'WILDER'],
    title: 'RSI Screener',
    module: 'RSI',
    requiresSymbol: false,
    description: 'RSI screener — Wilder’s 14-period RSI for every watchlist name with overbought (≥70) / oversold (≤30) flags: a momentum-oscillator scan across the whole list (the chart’s RSI sub-pane is per-symbol).',
  },
  {
    code: 'MACD',
    aliases: ['MACDX', 'SIGNAL'],
    title: 'MACD Signals',
    module: 'MACD',
    requiresSymbol: false,
    description: 'MACD signal board — 12/26/9 MACD line, price-normalized histogram, and bull/bear state with a fresh-cross marker for every watchlist name: a trend-momentum scan across the list (the chart’s MACD is per-symbol).',
  },
  {
    code: 'ADX',
    aliases: ['DMI', 'DIRECTIONAL'],
    title: 'ADX / DMI',
    module: 'ADX',
    requiresSymbol: false,
    description: 'ADX / DMI board — Wilder’s trend-strength gauge per name: ADX (≥25 strong trend, <20 rangebound) with +DI / −DI directional indicators and which one leads. Answers “is there a trend, how strong, and which way”.',
  },
  {
    code: 'MFI',
    aliases: ['MONEYFLOW', 'MF'],
    title: 'Money Flow Index',
    module: 'MFI',
    requiresSymbol: false,
    description: 'Money Flow Index board — the volume-weighted RSI (typical price × volume, 14-period) per name with overbought (≥80) / oversold (≤20) flags: combines price and volume into one oscillator, distinct from RSI (price only) and OBV (cumulative).',
  },
  {
    code: 'SUPER',
    aliases: ['SUPERTREND', 'ST'],
    title: 'Supertrend',
    module: 'SUPER',
    requiresSymbol: false,
    description: 'Supertrend board — the ATR trend-follow regime per name: up / down direction, the ATR trailing-stop level, how far price sits from that stop, and a fresh-flip marker. A popular crypto trend signal across the whole watchlist.',
  },
  {
    code: 'TREND',
    aliases: ['PERSIST', 'MATREND'],
    title: 'MA Trend Persistence',
    module: 'TREND',
    requiresSymbol: false,
    description: 'MA trend-persistence board — how durably each name holds one side of its SMA: the current consecutive run of closes above (+) / below (−) the average, how far price sits from it, and the share of days spent above. Moving-average-relative trend, distinct from STREAK.',
  },
  {
    code: 'AROON',
    aliases: ['AROONOSC', 'TRENDAGE'],
    title: 'Aroon',
    module: 'AROON',
    requiresSymbol: false,
    description: 'Aroon board — trend by time-since-extreme per name: Aroon-Up / Aroon-Down (how recently the N-bar high vs low printed, 0–100) and the oscillator (up − down). Measures the age of the extreme, not price distance (distinct from HILO).',
  },
  {
    code: 'CCI',
    aliases: ['CCI20', 'COMMODITY'],
    title: 'CCI Oscillator',
    module: 'CCI',
    requiresSymbol: false,
    description: 'Commodity Channel Index board — each name’s typical price vs its average ÷ mean deviation, with overbought (≥+100) / oversold (≤−100) flags: a mean-deviation oscillator distinct from RSI (gains/losses) and MFI (volume-weighted).',
  },
  {
    code: 'KELT',
    aliases: ['KELTNER', 'KC'],
    title: 'Keltner Channel',
    module: 'KELT',
    requiresSymbol: false,
    description: 'Keltner channel board — an EMA midline wrapped by ATR-scaled bands per name: where the close sits in the channel (0 lower · 50 mid · 100 upper), the band width relative to price, and an up/down breakout flag when price closes outside. The ATR-based volatility-band complement to Bollinger (BB).',
  },
  {
    code: 'STOCH',
    aliases: ['STOCHASTIC', 'STOCH14', 'KD'],
    title: 'Stochastic',
    module: 'STOCH',
    requiresSymbol: false,
    description:
      "Stochastic oscillator board — Lane's %K (the close's position in its N-bar high-low range) and %D signal line per name, with overbought (≥80) / oversold (≤20) zones and a fresh %K-vs-%D crossover flag. A range-position oscillator, distinct from RSI (gains/losses), MFI (volume-weighted) and CCI (mean deviation).",
  },
  {
    code: 'DON',
    aliases: ['DONCHIAN', 'TURTLE', 'DC'],
    title: 'Donchian Channel',
    module: 'DON',
    requiresSymbol: false,
    description:
      'Donchian breakout board (the Turtle channel) — the prior N-bar highest-high / lowest-low channel per name: where the close sits in it (0 lower · 100 upper, exceeding on breakouts), the channel width relative to price, and an up/down flag on a new N-bar high / low. The pure price-extreme complement to the ATR (KELT) and stdev (BB) volatility bands.',
  },
  {
    code: 'VTX',
    aliases: ['VORTEX', 'VI'],
    title: 'Vortex',
    module: 'VTX',
    requiresSymbol: false,
    description:
      'Vortex indicator board — +VI / −VI trend-direction lines (up vs down vortex movement ÷ true range over N bars) per name, their signed difference, which line leads, and a fresh +VI/−VI crossover flag. A trend-direction board, distinct from ADX (strength only), Aroon (time-since-extreme) and Supertrend (ATR stop).',
  },
  {
    code: 'TTM',
    aliases: ['TTMSQUEEZE', 'SQZ'],
    title: 'TTM Squeeze',
    module: 'TTM',
    requiresSymbol: false,
    description:
      "TTM squeeze board (Carter) — flags when each name's Bollinger bands sit inside its Keltner channel (volatility compression → coiling), with a squeeze on/off state, a fired flag when it releases, and Carter's de-trended momentum (value, direction & rising/falling). A genuine BB-meets-KELT setup scanner.",
  },
  {
    code: 'ICHI',
    aliases: ['ICHIMOKU', 'CLOUD', 'KUMO'],
    title: 'Ichimoku Cloud',
    module: 'ICHI',
    requiresSymbol: false,
    description:
      'Ichimoku cloud board — the five-line system per name reduced to the latest signals: price vs the kumo (above = bull / below = bear / inside = neutral), the cloud colour (Senkou A vs B), a fresh Tenkan×Kijun cross, and the signed distance of the close from the cloud. The current cloud is read at the displaced supplier bar (displacement = Kijun).',
  },
  {
    code: 'PSAR',
    aliases: ['SAR', 'PARABOLIC'],
    title: 'Parabolic SAR',
    module: 'PSAR',
    requiresSymbol: false,
    description:
      "Parabolic SAR board (Wilder stop-and-reverse) — the trailing-stop trend per name: long (stop below price) / short (stop above), the signed distance of the close from the stop, the acceleration factor (trend maturity), and a fresh-flip flag when the stop reverses. An iterative trailing-stop system, distinct from the ATR-band Supertrend (SUPER).",
  },
  {
    code: 'WILLR',
    aliases: ['WILLIAMS', 'WPR'],
    title: 'Williams %R',
    module: 'WILLR',
    requiresSymbol: false,
    description:
      "Williams %R board — where each name's close sits in its N-bar high-low range on a 0 to −100 scale (0 = top, −100 = bottom), with overbought (≥−20) / oversold (≤−80) flags. A momentum oscillator close to Stochastic's %K but inverted and unsmoothed.",
  },
  {
    code: 'UO',
    aliases: ['ULTIMATE', 'ULTOSC'],
    title: 'Ultimate Oscillator',
    module: 'UO',
    requiresSymbol: false,
    description:
      "Ultimate Oscillator board (Larry Williams) — buying pressure ÷ true range blended over three timeframes (7/14/28) weighted 4:2:1 into a 0–100 reading per name, with overbought (≥70) / oversold (≤30) flags. Blends short/medium/long momentum to cut the false divergences single-period oscillators give.",
  },
  {
    code: 'TRIX',
    aliases: ['TRIPLE', 'TRIXOSC'],
    title: 'TRIX',
    module: 'TRIX',
    requiresSymbol: false,
    description:
      'TRIX board — the 1-period % rate-of-change of a triple-smoothed EMA of price per name, with its signal line (EMA of TRIX), the histogram (TRIX − signal), the zero-line side (up/down) and a fresh TRIX×signal cross. Triple smoothing filters the noise a single EMA leaves: a zero-line momentum oscillator, distinct from MACD (dual EMA).',
  },
  {
    code: 'CMO',
    aliases: ['CHANDE', 'CMO14'],
    title: 'Chande Momentum',
    module: 'CMO',
    requiresSymbol: false,
    description:
      'Chande Momentum Oscillator board — (Σ up-moves − Σ down-moves) ÷ their total × 100 over N bars per name, on a ±100 scale with overbought (≥+50) / oversold (≤−50) flags. Uses raw sums (not smoothed averages like RSI), so it swings harder: a distinct momentum gauge from the RSI / Stochastic / CCI family.',
  },
  {
    code: 'ELDER',
    aliases: ['ELDERRAY', 'ERAY'],
    title: 'Elder-Ray',
    module: 'ELDER',
    requiresSymbol: false,
    description:
      "Elder-Ray board (Alexander Elder) — bull power (high − EMA) and bear power (low − EMA) per name as a % of the trend EMA, with the EMA slope as the up/down trend filter. Shows whether buyers or sellers control price relative to the trend: a buyer/seller-pressure board distinct from the oscillator family.",
  },
  {
    code: 'FISHER',
    aliases: ['FISH', 'EHLERS'],
    title: 'Fisher Transform',
    module: 'FISHER',
    requiresSymbol: false,
    description:
      "Fisher Transform board (Ehlers) — normalizes each name's median price into its N-bar range and applies the Fisher transform to sharpen turning points, with the trigger line (prior Fisher) and a fresh Fisher×trigger cross. A reversal-oriented oscillator with crisper turns than the smooth momentum family.",
  },
  {
    code: 'DPO',
    aliases: ['DETREND', 'DETRENDED'],
    title: 'Detrended Price',
    module: 'DPO',
    requiresSymbol: false,
    description:
      "Detrended Price Oscillator board — each name's close from floor(N/2)+1 bars ago minus its N-bar SMA (as a % of the SMA), with an above/below cycle-mean flag. Strips the trend to expose the price cycle around the average; reaches back (never forward) so the screener has no look-ahead. A cycle-oriented oscillator, distinct from the trend/momentum family.",
  },
  {
    code: 'COPP',
    aliases: ['COPPOCK', 'COP'],
    title: 'Coppock Curve',
    module: 'COPP',
    requiresSymbol: false,
    description:
      "Coppock Curve board — a 10-period weighted MA of each name's summed 14- and 11-bar rate-of-change, with its zero-line side and a fresh trough (up) / peak (down) turn. A trough turn near/below zero is Coppock's classic long-term buy signal: a slow, bottom-spotting momentum gauge distinct from the fast oscillator family.",
  },
  {
    code: 'BOP',
    aliases: ['BALOP', 'BPOW'],
    title: 'Balance of Power',
    module: 'BOP',
    requiresSymbol: false,
    description:
      "Balance of Power board — (close − open) ÷ (high − low) per bar, smoothed over N bars on a −1..+1 scale, per name, with a buyers/sellers side and the latest candle's raw reading. Measures who won each candle (close vs open within the range): a simple buyer/seller-pressure gauge distinct from Elder-Ray.",
  },
  {
    code: 'ADL',
    aliases: ['ACCDIST', 'CHAIKINAD'],
    title: 'A/D Line',
    module: 'ADL',
    requiresSymbol: false,
    description:
      "Accumulation/Distribution line board (Chaikin) — the cumulative money-flow-volume line (close position in range × volume) per name, reported as its normalized slope over N bars (net flow ÷ volume), its trend, and a fresh N-bar A/D high (accumulation breakout) / low (distribution breakdown). A cumulative volume-flow gauge distinct from OBV.",
  },
  {
    code: 'CMF',
    aliases: ['CHAIKINMF', 'CMFLOW'],
    title: 'Chaikin Money Flow',
    module: 'CMF',
    requiresSymbol: false,
    description:
      "Chaikin Money Flow board — Σ(money-flow volume) ÷ Σ(volume) over N bars per name, bounded −1..+1, with a buyers/sellers side and a strong-flow flag (|CMF| ≥ 0.25). The bounded oscillator sibling of the A/D line: positive is accumulation, negative distribution.",
  },
  {
    code: 'FORCE',
    aliases: ['FORCEINDEX', 'EFI'],
    title: 'Force Index',
    module: 'FORCE',
    requiresSymbol: false,
    description:
      "Force Index board (Elder) — (close − priorClose) × volume, EMA-smoothed over N bars per name, normalized as FI ÷ (price × avg volume) so it's comparable across names, with a bulls/bears side and a rising/falling flag. Ties the size of each move to the volume behind it: a zero-line volume oscillator.",
  },
  {
    code: 'EOM',
    aliases: ['EMV', 'EASE'],
    title: 'Ease of Movement',
    module: 'EOM',
    requiresSymbol: false,
    description:
      "Ease of Movement board (Arms) — midpoint move × range ÷ volume, SMA-smoothed over N bars per name and normalized to a dimensionless index, with an up/down ease side. Measures how readily price moves relative to the volume required: positive = rose easily (big move on light volume), negative = fell easily. A volume/price-efficiency oscillator.",
  },
  {
    code: 'PVT',
    aliases: ['PRICEVOL', 'PVTREND'],
    title: 'Price Volume Trend',
    module: 'PVT',
    requiresSymbol: false,
    description:
      "Price Volume Trend board — the cumulative ((close − priorClose)/priorClose) × volume line per name, reported as its normalized slope over N bars (volume-weighted % return), its trend, and a fresh N-bar PVT high / low. Like OBV but scaled by the size of each move: a volume-confirmed trend line distinct from OBV and the A/D line.",
  },
  {
    code: 'MASS',
    aliases: ['MASSINDEX', 'MASSIDX'],
    title: 'Mass Index',
    module: 'MASS',
    requiresSymbol: false,
    description:
      "Mass Index board (Dorsey) — Σ over 25 bars of EMA9(range) ÷ EMA9(EMA9(range)) per name, with the reversal-bulge state: bulge (≥ 27), setup (bulged then awaiting the drop), fired (just fell below 26.5 — the reversal warning) or normal. Watches the high-low range expand then contract to anticipate turns; a volatility-of-range signal distinct from the directional oscillators.",
  },
  {
    code: 'QSTICK',
    aliases: ['QSTK', 'QS'],
    title: 'Qstick',
    module: 'QSTICK',
    requiresSymbol: false,
    description:
      "Qstick board (Chande) — the average candle body (close − open) over N bars per name, as a % of price, with an up/down body-bias side. Above zero means up-closes dominated the window (buying bias), below zero down-closes (selling bias): a simple candle-body sentiment gauge.",
  },
  {
    code: 'NVI',
    aliases: ['PVI', 'VOLINDEX'],
    title: 'Volume Index',
    module: 'NVI',
    requiresSymbol: false,
    description:
      "Volume Index board — the Negative & Positive Volume Index per name (cumulative lines that compound the daily return only on down-volume days, NVI = 'smart money', or up-volume days, PVI), each vs its own EMA signal. Reports NVI's distance from its EMA and the bull/bear regime of both — NVI above its EMA is the strongest bull-market tell.",
  },
  {
    code: 'CFO',
    aliases: ['FORECAST', 'CHANDEFO'],
    title: 'Chande Forecast',
    module: 'CFO',
    requiresSymbol: false,
    description:
      "Chande Forecast Oscillator board — 100 × (close − the least-squares regression-line fit over N bars) ÷ close, per name, on a zero line with an above/below-fit side. Measures how far price sits from its own regression trend: above zero means it's running ahead of the fit, below means it lags. A regression-based oscillator distinct from the moving-average family.",
  },
  {
    code: 'RWI',
    aliases: ['RANDOMWALK', 'RWALK'],
    title: 'Random Walk Index',
    module: 'RWI',
    requiresSymbol: false,
    description:
      "Random Walk Index board — per name, the max over look-backs k=2..N of price displacement ÷ (ATR(k)·√k), split into RWIhigh (up-trend strength) and RWIlow (down-trend strength). A reading ≥ 1 means price out-ran a same-volatility random walk — a genuine trend; below 1 reads as directionless noise. The signed RWI (+high / −low) sorts strongest up-trends → range → strongest down-trends.",
  },
  {
    code: 'STC',
    aliases: ['SCHAFF', 'TRENDCYCLE'],
    title: 'Schaff Trend Cycle',
    module: 'STC',
    requiresSymbol: false,
    description:
      "Schaff Trend Cycle board — per name, a 0–100 cyclical oscillator that runs a stochastic over the 23/50 MACD line, then a second smoothed stochastic over that, so it turns earlier than a plain MACD. ≥ 75 and rising flags a strengthening up-cycle, ≤ 25 a down-cycle; crosses of 25 / 75 are the common triggers. Shows the STC level, its bar-over-bar change, and the bull/bear/mid zone.",
  },
  {
    code: 'TSI',
    aliases: ['TRUESTRENGTH', 'TSTRENGTH'],
    title: 'True Strength Index',
    module: 'TSI',
    requiresSymbol: false,
    description:
      "True Strength Index board — per name, William Blau's double-smoothed momentum: 100 × EMA(EMA(Δclose, 25), 13) ÷ EMA(EMA(|Δclose|, 25), 13), with a 7-EMA signal line. Bounded ≈ ±100; above zero is net positive (bullish) momentum, below zero bearish, ±25 the common overbought/oversold extremes, and a cross of the signal line the usual trigger. Shows the TSI, its distance from the signal, and the OB/OS/mid zone.",
  },
  {
    code: 'ALERT',
    aliases: ['ALERTS', 'ALRT', 'AL'],
    title: 'Alerts',
    module: 'ALERT',
    requiresSymbol: false,
    description: 'Price & funding alerts — fire a toast / notification when a threshold is crossed.',
  },
  {
    code: 'N',
    aliases: ['NEWS', 'CN'],
    title: 'News',
    module: 'N',
    requiresSymbol: false,
    description: 'Headlines for a security, or top market news when no symbol is given.',
  },
  {
    code: 'TOP',
    aliases: ['MKT'],
    title: 'Top News',
    module: 'N',
    requiresSymbol: false,
    description: 'Top market-wide news headlines.',
  },
  {
    code: 'NOTE',
    aliases: ['NOTES', 'JRNL', 'MEMO'],
    title: 'Notes',
    module: 'NOTE',
    requiresSymbol: false,
    description: 'Free-form notes — global or per symbol, synced to your account.',
  },
  {
    code: 'RISK',
    aliases: ['SIZER', 'SIZE', 'POSITION'],
    title: 'Position Sizer',
    module: 'RISK',
    requiresSymbol: false,
    description: 'Risk-based position sizer — solve size from account, risk %, entry and stop.',
  },
  {
    code: 'CONV',
    aliases: ['CONVERT', 'NOTIONAL', 'SIZECONV'],
    title: 'Size Converter',
    module: 'CONV',
    requiresSymbol: true,
    description: 'Size / notional converter — convert between quantity, notional, % of account and margin at the live price.',
  },
  {
    code: 'KELLY',
    aliases: ['BETSIZE', 'OPTIMALF', 'KCRIT'],
    title: 'Kelly Sizer',
    module: 'KELLY',
    requiresSymbol: false,
    description: 'Kelly-criterion bet sizing — optimal bankroll fraction from win rate & payoff, with half/quarter Kelly, expectancy and breakeven win.',
  },
  {
    code: 'ROR',
    aliases: ['RUIN', 'RISKOFRUIN', 'ROFR'],
    title: 'Risk of Ruin',
    module: 'ROR',
    requiresSymbol: false,
    description: 'Risk-of-ruin simulator — probability of blowing up from win rate, payoff & risk-per-trade, with expected max drawdown and a survival curve.',
  },
  {
    code: 'LADDER',
    aliases: ['SCALEIN', 'RUNGS', 'SCALE'],
    title: 'Scale-in Ladder',
    module: 'LADDER',
    requiresSymbol: false,
    description: 'Scale-in ladder planner — spread a budget across limit rungs over a price range (flat/linear/geometric) for a blended average entry.',
  },
  {
    code: 'DCA',
    aliases: ['AVG', 'AVERAGE', 'BASIS'],
    title: 'DCA / Averaging',
    module: 'DCA',
    requiresSymbol: false,
    description: 'Average-cost calculator — blend fills into an average entry, P&L and a target-average solver.',
  },
  {
    code: 'LOG',
    aliases: ['JOURNAL', 'TJ', 'TRADELOG'],
    title: 'Trade Journal',
    module: 'LOG',
    requiresSymbol: false,
    description: 'Trade journal — log entries/exits, score R-multiples, and track win rate, expectancy and total R.',
  },
  {
    code: 'EQ',
    aliases: ['EQUITY', 'CURVE', 'DRAWDOWN'],
    title: 'Equity Curve',
    module: 'EQ',
    requiresSymbol: false,
    description: 'Trade-journal equity curve — cumulative R, drawdown and streaks from your scored trades.',
  },
  {
    code: 'PNL',
    aliases: ['FEE', 'FEES', 'ROE'],
    title: 'P&L Calculator',
    module: 'PNL',
    requiresSymbol: false,
    description: 'Trade P&L & fee calculator — gross/net P&L, ROE, fees paid and fee-inclusive break-even.',
  },
  {
    code: 'ACCT',
    aliases: ['ACCOUNT'],
    title: 'Account',
    module: 'ACCT',
    requiresSymbol: false,
    description: 'Manage your account — change password, sessions, and (admin) users.',
  },
  {
    code: 'PREF',
    aliases: ['SETTINGS', 'SET', 'PREFS', 'CONFIG'],
    title: 'Preferences',
    module: 'PREF',
    requiresSymbol: false,
    description: 'Terminal preferences — display density, ticker, default chart timeframe, alert delivery.',
  },
  {
    code: 'REPORT',
    aliases: ['EXPORT', 'CSV', 'REPORTS'],
    title: 'Reports / Export',
    module: 'REPORT',
    requiresSymbol: false,
    description: 'Export your data to CSV — journal, transactions, positions, alert triggers and watchlists.',
  },
  {
    code: 'SECF',
    aliases: ['FIND', 'SEARCH', 'SRCH'],
    title: 'Security Finder',
    module: 'SECF',
    requiresSymbol: false,
    description: 'Search for securities by ticker or name.',
  },
  {
    code: 'HELP',
    aliases: ['H', '?'],
    title: 'Help',
    module: 'HELP',
    requiresSymbol: false,
    description: 'List of available commands and how to use the terminal.',
  },
];

const BY_CODE = new Map<string, CommandDef>();
for (const cmd of COMMANDS) {
  BY_CODE.set(cmd.code, cmd);
  for (const alias of cmd.aliases) BY_CODE.set(alias, cmd);
}

export function lookupCommand(token: string): CommandDef | undefined {
  return BY_CODE.get(token.trim().toUpperCase());
}

/** All distinct command codes (for autocomplete), excluding aliases. */
export const COMMAND_CODES = COMMANDS.map((c) => c.code);
