import type { CommandDef } from '../registry';

/** Market data, charts, microstructure, the Solana suite, screeners and the heatmap/overview. */
export const MARKET_COMMANDS: CommandDef[] = [
  {
    code: 'DES',
    aliases: ['DESC', 'DS'],
    title: 'Security Description',
    module: 'DES',
    requiresSymbol: true,
    description: 'Snapshot quote, key stats and session detail for a security.',
  },
  {
    code: 'GP',
    aliases: ['CHART', 'G', 'GRAPH'],
    title: 'Price Graph',
    module: 'GP',
    requiresSymbol: true,
    description: 'Historical price chart (daily candles).',
    params: { interval: '1d', range: '6mo' },
  },
  {
    code: 'GIP',
    aliases: ['INTRADAY'],
    title: 'Intraday Graph',
    module: 'GP',
    requiresSymbol: true,
    description: 'Intraday price chart (5-minute candles).',
    params: { interval: '5m', range: '1d' },
  },
  {
    code: 'HP',
    aliases: ['HISTORY', 'HISTPX', 'OHLC'],
    title: 'Historical Prices',
    module: 'HP',
    requiresSymbol: true,
    description:
      'Historical prices — a tabular OHLCV history per bar (open/high/low/close, change% vs the prior close, volume) with 5D / 1M / 3M / 1Y / 5Y lookbacks, a period summary (high/low, total change, avg volume, up/down days) and sortable date / change% / volume columns. The data-table complement to the chart (G / GIP).',
  },
  {
    code: 'COMP',
    aliases: ['COMPARE', 'CMP', 'REL'],
    title: 'Compare',
    module: 'COMP',
    requiresSymbol: false,
    description: 'Overlay several symbols rebased to % change to compare performance.',
    params: { interval: '1d', range: '6mo' },
  },
  {
    code: 'RATIO',
    aliases: ['SPREAD'],
    title: 'Ratio / Spread',
    module: 'RATIO',
    requiresSymbol: false,
    description: 'Chart the ratio (A/B) or spread (A−B) between two symbols over time.',
    params: { interval: '1d', range: '6mo' },
  },
  {
    code: 'PAIR',
    aliases: ['PAIRS', 'ZSCORE', 'STATARB'],
    title: 'Pairs Z-Score',
    module: 'PAIR',
    requiresSymbol: false,
    description: 'Pairs / stat-arb monitor — ratio of two symbols with rolling mean ±σ bands, a z-score oscillator and mean-reversion half-life.',
  },
  {
    code: 'BOOK',
    aliases: ['DOM', 'OB'],
    title: 'Order Book',
    module: 'BOOK',
    requiresSymbol: true,
    description: 'Live Level-2 order book / depth of market (best on crypto).',
  },
  {
    code: 'DEPTH',
    aliases: ['DHEAT', 'OBHEAT', 'DOMHEAT'],
    title: 'Depth Heatmap',
    module: 'DEPTH',
    requiresSymbol: true,
    description: 'Order-book depth heatmap — resting liquidity over time as a price × time grid, with the mid track.',
  },
  {
    code: 'DEX',
    aliases: ['ONCHAIN', 'POOLS', 'DEXPOOLS'],
    title: 'DEX Pools',
    module: 'DEX',
    requiresSymbol: true,
    description: 'On-chain / DEX liquidity pools for an asset — price, TVL, 24h volume, fee tier and an estimated swap price-impact per pool, plus the CEX↔DEX basis (premium/discount), with a live/synthetic data-honesty badge (synthetic until an on-chain source is configured).',
  },
  {
    code: 'SOLNET',
    aliases: ['SOLANA', 'SNET'],
    title: 'Solana Network',
    module: 'SOLNET',
    requiresSymbol: false,
    description: 'Solana network health — current slot, epoch progress, TPS, active validators, total stake, and circulating/total SOL supply with a live market cap. Read-only public-RPC reads (non-custodial), with a live/synthetic data-honesty badge (synthetic until MIDAS_SOLANA_RPC is set).',
  },
  {
    code: 'SWAL',
    aliases: ['SOLWALLET', 'SWALLET'],
    title: 'Solana Wallet',
    module: 'SWAL',
    requiresSymbol: false,
    description: 'Read-only Solana wallet inspector — paste a public base-58 address to see its SOL balance and SPL token holdings priced to USD. Non-custodial by construction: no key, no signing, no transaction ever, with a live/synthetic data-honesty badge.',
  },
  {
    code: 'STREND',
    aliases: ['SOLTREND', 'SOLTRENDING'],
    title: 'Solana Trending',
    module: 'STREND',
    requiresSymbol: false,
    description: 'Trending Solana tokens ranked by 24h DEX volume — price, 24h change, volume, pool liquidity and the top venue (Raydium/Orca/Meteora) per token. Read-only market discovery from a DEX aggregator, with a live/synthetic data-honesty badge (synthetic until MIDAS_DEX_SOURCE=geckoterminal).',
  },
  {
    code: 'SOLDEX',
    aliases: ['SOLPOOLS', 'SPOOLS'],
    title: 'Solana DEX Pools',
    module: 'SOLDEX',
    requiresSymbol: true,
    description: "A base asset's liquidity across Solana DEXes (Raydium, Orca, Meteora, Phoenix, Lifinity) — price, TVL, 24h volume and fee tier per pool, with a VWAP/TVL roll-up. Read-only, non-custodial, with a live/synthetic data-honesty badge (synthetic until MIDAS_DEX_SOURCE=geckoterminal).",
  },
  {
    code: 'SVAL',
    aliases: ['SOLVAL', 'VALIDATORS'],
    title: 'Solana Validators',
    module: 'SVAL',
    requiresSymbol: false,
    description: 'The Solana validator leaderboard ranked by active stake — identity, stake, share of network, commission and voting status (voting/delinquent), with network totals. Read-only public-RPC read (getVoteAccounts), non-custodial, with a live/synthetic data-honesty badge (synthetic until MIDAS_SOLANA_RPC is set).',
  },
  {
    code: 'SSTAKE',
    aliases: ['SOLSTAKE', 'STAKEYIELD'],
    title: 'Solana Staking',
    module: 'SSTAKE',
    requiresSymbol: false,
    description: 'Solana native staking economics — nominal and real (epoch-compounded) staking APY, current network inflation and the staked ratio (share of supply staked), derived from RPC. Read-only, non-custodial, with a live/synthetic data-honesty badge (synthetic until MIDAS_SOLANA_RPC is set).',
  },
  {
    code: 'SPL',
    aliases: ['SPLTOKEN', 'SOLTOKEN'],
    title: 'SPL Token',
    module: 'SPL',
    requiresSymbol: false,
    description: 'Read-only SPL token (mint) explorer — paste a mint to see supply, decimals, program and the mint/freeze authorities that decide token safety (an active mint authority can inflate supply; an active freeze authority can freeze accounts). Read-only public-RPC read (getTokenSupply/getAccountInfo), non-custodial, with a live/synthetic data-honesty badge (synthetic until MIDAS_SOLANA_RPC is set).',
  },
  {
    code: 'SJUP',
    aliases: ['SOLSWAP', 'JUPITER'],
    title: 'Solana Swap Quote',
    module: 'SJUP',
    requiresSymbol: false,
    description: 'Read-only Jupiter swap quotes — pick input/output tokens and an amount to see the best-route output, price impact and AMM hops. Quote only: Midas fetches a price estimate and never builds, signs or sends a swap, preserving the non-custodial invariant. Live via MIDAS_SOLANA_JUPITER, with a live/synthetic data-honesty badge.',
  },
  {
    code: 'SOLMKT',
    aliases: ['SOLMARKET', 'SOLOVERVIEW'],
    title: 'Solana Market',
    module: 'SOLMKT',
    requiresSymbol: false,
    description: "Solana ecosystem market overview — SOL's spot price, an aggregate 24h-volume and liquidity roll-up across the busiest tokens, and a compact top-tokens list. The macro companion to STREND's ranked list. Read-only market data, with a live/synthetic data-honesty badge (synthetic until MIDAS_DEX_SOURCE=geckoterminal).",
  },
  {
    code: 'TAS',
    aliases: ['PRINTS', 'TS', 'TRADES'],
    title: 'Time & Sales',
    module: 'TAS',
    requiresSymbol: true,
    description: 'Live streaming trade prints (time & sales).',
  },
  {
    code: 'CVD',
    aliases: ['FLOW', 'OFD', 'DELTA'],
    title: 'Order Flow',
    module: 'CVD',
    requiresSymbol: true,
    description: 'Order-flow / cumulative volume delta — buy vs sell pressure over time with a per-window delta histogram.',
  },
  {
    code: 'IMB',
    aliases: ['IMBALANCE', 'OBI', 'PRESSURE'],
    title: 'Book Imbalance',
    module: 'IMB',
    requiresSymbol: true,
    description: 'Order-book imbalance — top-N bid vs ask depth pressure over time with a live gauge.',
  },
  {
    code: 'LQA',
    aliases: ['LIQUIDITY', 'SPREADS', 'MKTQUAL'],
    title: 'Liquidity',
    module: 'LQA',
    requiresSymbol: false,
    description: 'Liquidity board — watchlist ranked by bid/ask spread (bps) and top-of-book depth.',
  },
  {
    code: 'ALLQ',
    aliases: ['XQ', 'VENUES'],
    title: 'Multi-Exchange Quotes',
    module: 'ALLQ',
    requiresSymbol: true,
    description: 'Compare a pair across exchanges — best bid/ask and cross-exchange spread.',
  },
  {
    code: 'DXV',
    aliases: ['FUNDV', 'VFUND', 'VENUEDERIVS'],
    title: 'Derivatives by Venue',
    module: 'DXV',
    requiresSymbol: true,
    description:
      "Cross-exchange derivatives — a perp's funding rate and open interest across every venue in the compare set (Binance, OKX, Bybit, …), side by side. Funding diverges across exchanges, so the board surfaces the cross-venue funding spread (Δfund) as a funding-arbitrage signal (long the cheapest venue, short the dearest) and aggregates open interest. Complements ALLQ (spot quotes across venues) and FUND (single-venue funding/OI/liqs). Crypto-only (ccxt provider).",
  },
  {
    code: 'FUND',
    aliases: ['OI', 'LIQ', 'PERP'],
    title: 'Derivatives',
    module: 'FUND',
    requiresSymbol: true,
    description: 'Perp funding rate, open interest and recent liquidations.',
  },
  {
    code: 'FUNDR',
    aliases: ['RATES'],
    title: 'Funding Rates',
    module: 'FUNDR',
    requiresSymbol: false,
    description: 'Funding rates & open interest across the top perps — sortable board.',
  },
  {
    code: 'FUNDX',
    aliases: ['FUNDISP', 'FDISP', 'FARB'],
    title: 'Funding Dispersion',
    module: 'FUNDX',
    requiresSymbol: false,
    description:
      "Cross-venue funding dispersion — for the top perps by volume, the funding-rate spread across the compare set (Binance, OKX, Bybit, …), ranked widest-first. The market-wide funding-arbitrage scanner: long the cheapest-funded venue, short the dearest. Extends DXV (one perp across venues) to the whole board and complements FUNDR (single-venue funding board). Crypto-only (ccxt provider).",
  },
  {
    code: 'XARB',
    aliases: ['ARBBOARD', 'VARB', 'ARBSCAN'],
    title: 'Arb Screener',
    module: 'XARB',
    requiresSymbol: false,
    description:
      'Cross-venue arb screener — for the top symbols by volume, how far the price disagrees across the compare set (Binance, OKX, Bybit, …), ranked by dispersion. Surfaces the sell-here (highest bid) and buy-here (lowest ask) legs and flags crossed books (a gross-of-fees arb). The market-wide board version of ALLQ/ARB (one symbol across venues). Crypto-only (ccxt provider).',
  },
  {
    code: 'OIV',
    aliases: ['CROWD', 'OICONC', 'XOI'],
    title: 'OI by Venue',
    module: 'OIV',
    requiresSymbol: false,
    description:
      "Cross-venue open-interest / crowding board — for the top perps by volume, aggregate open interest across the compare set (Binance, OKX, Bybit, …) plus how concentrated it is on one venue (top-venue share + a Herfindahl index), ranked by total OI. High OI concentrated on a single venue is crowding / venue risk. The size-and-positioning companion to FUNDX (funding) and XARB (price). Crypto-only (ccxt provider).",
  },
  {
    code: 'LIQS',
    aliases: ['LIQUIDATIONS', 'REKT'],
    title: 'Liquidations',
    module: 'LIQS',
    requiresSymbol: false,
    description: 'Market-wide liquidations feed across the top perps.',
  },
  {
    code: 'SCR',
    aliases: ['EQS', 'SCREEN', 'MOVERS'],
    title: 'Screener',
    module: 'SCR',
    requiresSymbol: false,
    description: 'Screen crypto markets by volume, 24h change or price.',
  },
  {
    code: 'HEAT',
    aliases: ['MAP', 'HM'],
    title: 'Market Heatmap',
    module: 'HEAT',
    requiresSymbol: false,
    description: 'Treemap of the market — tiles sized by volume, colored by 24h change.',
  },
  {
    code: 'MOV',
    aliases: ['OVERVIEW'],
    title: 'Market Overview',
    module: 'MOV',
    requiresSymbol: false,
    description: 'Market dashboard — top gainers, losers, most active and breadth.',
  },
  {
    code: 'MCAP',
    aliases: ['TOPCOINS', 'MARKETCAP', 'COINS'],
    title: 'Top Coins',
    module: 'TOP',
    requiresSymbol: false,
    description:
      'Top coins by market cap — rank, price, 24h change, market cap, fully-diluted valuation, circulating supply and category. Reference data an exchange feed cannot produce alone (a CEX ticker has no circulating supply, so no honest market cap), with a live/synthetic data-honesty badge (synthetic until a live reference source is configured).',
  },
];
