import type { CommandDef } from '../registry';

/** Cross-asset analytics: correlation, risk/return, volatility, backtesting, momentum, seasonality, carry, arb. */
export const QUANT_COMMANDS: CommandDef[] = [
  {
    code: 'CORR',
    aliases: ['COR', 'CORREL'],
    title: 'Correlation Matrix',
    module: 'CORR',
    requiresSymbol: false,
    description: 'Return-correlation grid across your watchlist symbols.',
  },
  {
    code: 'AVGCORR',
    aliases: ['AVGCOR', 'CORRREGIME', 'MEANCORR'],
    title: 'Correlation Regime',
    module: 'AVGCORR',
    requiresSymbol: false,
    description: 'Average-correlation regime — mean pairwise correlation across your watchlist over time; high = risk-off, low = dispersion.',
  },
  {
    code: 'BREADTH',
    aliases: ['ADLINE', 'PARTICIPATION', 'ABOVEMA'],
    title: 'Breadth Oscillator',
    module: 'BREADTH',
    requiresSymbol: false,
    description: 'Market-breadth oscillator — the % of your watchlist above its N-day moving average over time; high = broad strength, low = weakness.',
  },
  {
    code: 'BETA',
    aliases: ['BTCBETA', 'BETAS'],
    title: 'Beta vs BTC',
    module: 'BETA',
    requiresSymbol: false,
    description: 'Beta board — each watchlist symbol’s beta, correlation and R² vs BTC from daily returns.',
  },
  {
    code: 'CAPTURE',
    aliases: ['UPDOWN', 'CAPRATIO', 'UPCAPTURE'],
    title: 'Up/Down Capture',
    module: 'CAPTURE',
    requiresSymbol: false,
    description: 'Up/down capture vs BTC — how much of BTC’s up vs down moves each watchlist symbol catches, with the capture ratio.',
  },
  {
    code: 'RBETA',
    aliases: ['ROLLBETA', 'RCORR', 'BETAHIST'],
    title: 'Rolling Beta',
    module: 'RBETA',
    requiresSymbol: true,
    description: 'Rolling beta & correlation vs BTC — how a symbol’s sensitivity to Bitcoin drifts over a trailing window.',
  },
  {
    code: 'SCAT',
    aliases: ['SCATTER', 'REGRESS', 'BETAPLOT'],
    title: 'Returns Scatter',
    module: 'SCAT',
    requiresSymbol: true,
    description: 'Returns scatter vs BTC — daily returns with the fitted regression line (beta, alpha, R²).',
  },
  {
    code: 'VPVR',
    aliases: ['VP', 'VOLPROFILE', 'VBP'],
    title: 'Volume Profile',
    module: 'VPVR',
    requiresSymbol: true,
    description: 'Volume profile (VPVR) — traded volume binned by price with the Point of Control and 70% value area (VAH/VAL).',
  },
  {
    code: 'SHARPE',
    aliases: ['SORTINO', 'RISKADJ', 'RAR'],
    title: 'Risk-Adjusted',
    module: 'SHARPE',
    requiresSymbol: false,
    description: 'Risk-adjusted return board — Sharpe & Sortino (annualized) with annualized return and vol across your watchlist.',
  },
  {
    code: 'RSHARPE',
    aliases: ['ROLLSHARPE', 'RSHARP', 'SHARPEHIST'],
    title: 'Rolling Sharpe',
    module: 'RSHARPE',
    requiresSymbol: true,
    description: 'Rolling Sharpe — the trailing annualized risk-adjusted return over a moving window, showing when an edge strengthened or decayed.',
  },
  {
    code: 'DD',
    aliases: ['DRAWDOWN', 'UNDERWATER', 'MDD'],
    title: 'Drawdown',
    module: 'DD',
    requiresSymbol: false,
    description: 'Drawdown monitor — max & current drawdown, time underwater and an underwater curve across your watchlist.',
  },
  {
    code: 'CALMAR',
    aliases: ['MARRATIO', 'RETDD', 'CALMARRATIO'],
    title: 'Calmar Ratio',
    module: 'CALMAR',
    requiresSymbol: false,
    description: 'Calmar-ratio board — annualized return ÷ max drawdown across your watchlist, ranking return per unit of worst drawdown.',
  },
  {
    code: 'CAL',
    aliases: ['CALENDAR', 'EVENTS', 'ECON'],
    title: 'Market Calendar',
    module: 'CAL',
    requiresSymbol: false,
    description: 'Upcoming market timing — funding settlements, options/futures expiries and candle closes.',
  },
  {
    code: 'VOL',
    aliases: ['VOLATILITY', 'ATR', 'RV'],
    title: 'Volatility',
    module: 'VOL',
    requiresSymbol: false,
    description: 'Volatility dashboard — realized vol, ATR and high-low range ranked across your watchlist.',
  },
  {
    code: 'VAR',
    aliases: ['DIST', 'HIST', 'CVAR'],
    title: 'Returns / VaR',
    module: 'VAR',
    requiresSymbol: true,
    description: 'Return distribution & risk — histogram with vol, skew, kurtosis and historical VaR / expected shortfall.',
  },
  {
    code: 'SKEW',
    aliases: ['SHAPE', 'KURTOSIS'],
    title: 'Return Shape',
    module: 'SKEW',
    requiresSymbol: false,
    description: 'Return-shape board — skewness & excess kurtosis of each watchlist symbol’s daily returns, flagging fat-tailed & asymmetric names.',
  },
  {
    code: 'VTS',
    aliases: ['VOLTERM', 'TERM', 'VTERM'],
    title: 'Vol Term Structure',
    module: 'VTS',
    requiresSymbol: true,
    description: 'Volatility term structure — realized vol across 7d…180d lookbacks, flagging rich/cheap near-term vol.',
  },
  {
    code: 'VCONE',
    aliases: ['VOLCONE', 'VCONES', 'RVCONE'],
    title: 'Vol Cones',
    module: 'VCONE',
    requiresSymbol: true,
    description: 'Volatility cones — realized-vol percentiles across 10…120d horizons with the current vol overlaid, flagging rich/cheap.',
  },
  {
    code: 'MC',
    aliases: ['MONTECARLO', 'PROJECT', 'CONE'],
    title: 'Monte Carlo',
    module: 'MC',
    requiresSymbol: true,
    description: 'Monte Carlo projection cone — GBM price forecast fan (5–95 percentiles) from historical drift & vol.',
  },
  {
    code: 'BACKTEST',
    aliases: ['BT', 'STRATEGY', 'SMACROSS', 'RSIBT', 'BOLLBT', 'MACDBT'],
    title: 'Backtest',
    module: 'BACKTEST',
    requiresSymbol: true,
    description: 'Strategy backtest — SMA-crossover, RSI mean-reversion, Bollinger-band reversion or MACD crossover: strategy equity vs buy & hold with total return, max drawdown, win rate & trade count.',
  },
  {
    code: 'MOM',
    aliases: ['MOMENTUM', 'RS', 'STRENGTH'],
    title: 'Momentum',
    module: 'MOM',
    requiresSymbol: false,
    description: 'Momentum / relative-strength board — 24h/7d/30d returns ranked across your watchlist.',
  },
  {
    code: 'STRETCH',
    aliases: ['OVERSOLD', 'BBANDS', 'MEANREV'],
    title: 'Stretch Screener',
    module: 'STRETCH',
    requiresSymbol: false,
    description: 'Mean-reversion screener — watchlist ranked by z-score & Bollinger %B vs its moving average, flagging overbought/oversold.',
  },
  {
    code: 'HURST',
    aliases: ['REGIME', 'TRENDREV', 'FRACTAL'],
    title: 'Trend / Revert',
    module: 'HURST',
    requiresSymbol: false,
    description: 'Trend vs mean-reversion board — each watchlist symbol’s Hurst exponent (R/S) classifying trending, mean-reverting or random-walk.',
  },
  {
    code: 'EFFICIENCY',
    aliases: ['EFFRATIO', 'KER'],
    title: 'Trend Efficiency',
    module: 'EFFICIENCY',
    requiresSymbol: false,
    description: 'Trend-efficiency board — Kaufman’s Efficiency Ratio (net move ÷ path) ranks how clean vs choppy each watchlist symbol’s trend is.',
  },
  {
    code: 'SCAN',
    aliases: ['SCANNER', 'SIGNALS', 'SETUP'],
    title: 'Signal Scan',
    module: 'SCAN',
    requiresSymbol: false,
    description: 'Signal scanner — watchlist SMA20/50 trend, RSI(14) overbought/oversold and 52-week range position, ranked by a bull/bear score; filter by criteria, save named scans, and watch a scan to be notified when new symbols match.',
  },
  {
    code: 'MTF',
    aliases: ['MULTITF', 'TIMEFRAMES', 'MTREND'],
    title: 'Multi-Timeframe',
    module: 'MTF',
    requiresSymbol: true,
    description: 'Multi-timeframe trend — SMA trend & RSI across 1H/1D/1W/1M with a consensus read of whether the frames are in gear.',
  },
  {
    code: 'RRG',
    aliases: ['ROTATION', 'ROT'],
    title: 'Rotation (RRG)',
    module: 'RRG',
    requiresSymbol: false,
    description: 'Relative rotation graph — watchlist symbols by RS-Ratio × RS-Momentum vs BTC, with rotation tails.',
  },
  {
    code: 'SEAS',
    aliases: ['SEASON', 'SEASONALITY', 'TOD'],
    title: 'Seasonality',
    module: 'SEAS',
    requiresSymbol: true,
    description: 'Returns seasonality — average return by UTC hour-of-day and day-of-week as a heat grid.',
  },
  {
    code: 'MRET',
    aliases: ['MONTHLY', 'MRETURNS', 'CALRET'],
    title: 'Monthly Returns',
    module: 'MRET',
    requiresSymbol: true,
    description: 'Monthly returns heatmap — month-over-month % as a year × month grid with compounded year totals.',
  },
  {
    code: 'RCAL',
    aliases: ['RETCAL', 'DRET', 'DAILYRET'],
    title: 'Returns Calendar',
    module: 'RCAL',
    requiresSymbol: true,
    description: 'Daily returns calendar — a contribution-style heatmap of daily % returns with best/worst day, positive-day rate and current streak.',
  },
  {
    code: 'CARRY',
    aliases: ['CASHCARRY', 'CARRYTRADE'],
    title: 'Funding Carry',
    module: 'CARRY',
    requiresSymbol: false,
    description: 'Funding-carry board — perps ranked by funding APR with spot-vs-perp basis and the carry leg.',
  },
  {
    code: 'FPL',
    aliases: ['FUNDPNL', 'CARRYPNL', 'FPNL'],
    title: 'Funding P&L',
    module: 'FPL',
    requiresSymbol: true,
    description: 'Funding P&L forecaster — project a perp position’s carry over a horizon at the current funding rate.',
  },
  {
    code: 'FRH',
    aliases: ['FUNDHIST', 'FRATE', 'FUNDINGHIST'],
    title: 'Funding History',
    module: 'FRH',
    requiresSymbol: true,
    description: 'Funding-rate history — a perp’s funding settlements over time with the average and current APR.',
  },
  {
    code: 'PREM',
    aliases: ['PREMIUM'],
    title: 'Basis Monitor',
    module: 'PREM',
    requiresSymbol: true,
    description: 'Perp basis monitor — premium vs spot, funding rate & APR, with a live premium history.',
  },
  {
    code: 'ARB',
    aliases: ['ARBITRAGE', 'XSPREAD'],
    title: 'Arb Scanner',
    module: 'ARB',
    requiresSymbol: true,
    description: 'Cross-exchange arb scanner — best bid/ask across venues, spread % and crossed-book flag.',
  },
  {
    code: 'SLIP',
    aliases: ['SLIPPAGE', 'IMPACT'],
    title: 'Slippage',
    module: 'SLIP',
    requiresSymbol: true,
    description: 'Slippage estimator — average fill & market impact for an order size, walking the live book.',
  },
  {
    code: 'TWAP',
    aliases: ['EXEC', 'ALGO', 'SLICE'],
    title: 'Execution (TWAP)',
    module: 'TWAP',
    requiresSymbol: true,
    description: 'TWAP execution planner — slice a large order over time and compare impact vs an aggressive block.',
  },
];
