import type { CommandDef } from '../registry';

/** Alerts, news, notes, calculators, preferences, reports, the board catalog and help. */
export const UTILITY_COMMANDS: CommandDef[] = [
  {
    code: 'ALERT',
    aliases: ['ALERTS', 'ALRT', 'AL'],
    title: 'Alerts',
    module: 'ALERT',
    requiresSymbol: false,
    symbolOptional: true,
    args: 'price',
    description:
      'Price & funding alerts — fire a toast / notification when a threshold is crossed. Quick-arm from the command line: `BTC/USDT ALERT 70000` (crosses), `ALERT > 70000` (rises ≥) or `ALERT < 70000` (falls ≤). Command-line alerts are local — they fire while this terminal tab is open.',
  },
  {
    code: 'N',
    aliases: ['NEWS', 'CN'],
    title: 'News',
    module: 'N',
    requiresSymbol: false,
    symbolOptional: true,
    description: 'Headlines for a security, or top market news when no symbol is given.',
  },
  {
    code: 'TOP',
    aliases: ['MKT'],
    title: 'Top News',
    module: 'N',
    requiresSymbol: false,
    description: 'Top market-wide news headlines.',
  },
  {
    code: 'NOTE',
    aliases: ['NOTES', 'JRNL', 'MEMO'],
    title: 'Notes',
    module: 'NOTE',
    requiresSymbol: false,
    description: 'Free-form notes — global or per symbol, synced to your account.',
  },
  {
    code: 'RISK',
    aliases: ['SIZER', 'SIZE', 'POSITION'],
    title: 'Position Sizer',
    module: 'RISK',
    requiresSymbol: false,
    description: 'Risk-based position sizer — solve size from account, risk %, entry and stop.',
  },
  {
    code: 'CONV',
    aliases: ['CONVERT', 'NOTIONAL', 'SIZECONV'],
    title: 'Size Converter',
    module: 'CONV',
    requiresSymbol: true,
    description: 'Size / notional converter — convert between quantity, notional, % of account and margin at the live price.',
  },
  {
    code: 'KELLY',
    aliases: ['BETSIZE', 'OPTIMALF', 'KCRIT'],
    title: 'Kelly Sizer',
    module: 'KELLY',
    requiresSymbol: false,
    description: 'Kelly-criterion bet sizing — optimal bankroll fraction from win rate & payoff, with half/quarter Kelly, expectancy and breakeven win.',
  },
  {
    code: 'ROR',
    aliases: ['RUIN', 'RISKOFRUIN', 'ROFR'],
    title: 'Risk of Ruin',
    module: 'ROR',
    requiresSymbol: false,
    description: 'Risk-of-ruin simulator — probability of blowing up from win rate, payoff & risk-per-trade, with expected max drawdown and a survival curve.',
  },
  {
    code: 'LADDER',
    aliases: ['SCALEIN', 'RUNGS', 'SCALE'],
    title: 'Scale-in Ladder',
    module: 'LADDER',
    requiresSymbol: false,
    description: 'Scale-in ladder planner — spread a budget across limit rungs over a price range (flat/linear/geometric) for a blended average entry.',
  },
  {
    code: 'DCA',
    aliases: ['AVG', 'AVERAGE', 'BASIS'],
    title: 'DCA / Averaging',
    module: 'DCA',
    requiresSymbol: false,
    description: 'Average-cost calculator — blend fills into an average entry, P&L and a target-average solver.',
  },
  {
    code: 'LOG',
    aliases: ['JOURNAL', 'TJ', 'TRADELOG'],
    title: 'Trade Journal',
    module: 'LOG',
    requiresSymbol: false,
    description: 'Trade journal — log entries/exits, score R-multiples, and track win rate, expectancy and total R.',
  },
  {
    code: 'EQ',
    aliases: ['EQUITY', 'CURVE'],
    title: 'Equity Curve',
    module: 'EQ',
    requiresSymbol: false,
    description: 'Trade-journal equity curve — cumulative R, drawdown and streaks from your scored trades.',
  },
  {
    code: 'PNL',
    aliases: ['FEE', 'FEES', 'ROE'],
    title: 'P&L Calculator',
    module: 'PNL',
    requiresSymbol: false,
    description: 'Trade P&L & fee calculator — gross/net P&L, ROE, fees paid and fee-inclusive break-even.',
  },
  {
    code: 'ACCT',
    aliases: ['ACCOUNT'],
    title: 'Account',
    module: 'ACCT',
    requiresSymbol: false,
    description: 'Manage your account — change password, sessions, and (admin) users.',
  },
  {
    code: 'PREF',
    aliases: ['SETTINGS', 'SET', 'PREFS', 'CONFIG'],
    title: 'Preferences',
    module: 'PREF',
    requiresSymbol: false,
    description: 'Terminal preferences — display density, ticker, default chart timeframe, alert delivery.',
  },
  {
    code: 'REPORT',
    aliases: ['EXPORT', 'CSV', 'REPORTS'],
    title: 'Reports / Export',
    module: 'REPORT',
    requiresSymbol: false,
    description: 'Export your data to CSV — journal, transactions, positions, alert triggers and watchlists.',
  },
  {
    code: 'SECF',
    aliases: ['FIND', 'SEARCH', 'SRCH'],
    title: 'Security Finder',
    module: 'SECF',
    requiresSymbol: false,
    args: 'text',
    description:
      'Search for securities by ticker or name (`SECF bitcoin`). Ticker collides with a command (ARB, COMP, W, FLOW…)? Prefix it with `$` — `$ARB` forces symbol resolution — or use the pair form `ARB/USDT`.',
  },
  {
    code: 'BOARDS',
    aliases: ['CATALOG', 'SCREENS', 'INDICATORS'],
    title: 'Screener Catalog',
    module: 'BOARDS',
    requiresSymbol: false,
    description:
      'Screener catalog — a single searchable, categorized directory of every indicator/analytics screener board in the terminal (Momentum, Trend, Volatility, Volume, Cycles, Risk & Performance). Type to filter by code/name/description and click a code to open it, instead of memorizing ~115 mnemonics. The list is derived from the command registry itself.',
  },
  {
    code: 'HELP',
    aliases: ['H', '?'],
    title: 'Help',
    module: 'HELP',
    requiresSymbol: false,
    description:
      'List of available commands and how to use the terminal. Grammar: SYMBOL COMMAND [args] — e.g. `BTC/USDT GP 1h`, `BTC/USDT ALERT > 70000`; `$` forces a ticker that shadows a command (`$ARB`).',
  },
];
